### PR TITLE
EVSRESTAPI-329: Using concept active flag instead of "Retired_Concept" status.

### PR DESCRIPTION
**Pull request by twkatadin**

### CODE REVIEW

**Comment by twkatadin** [comment]
Also included RDFBROWSER-390: Made history replacement code link to replacement concept

**Review by bcarlsenca — COMMENTED** [review]
This isn't quite right, because for an inactive NCIt concept it will only show the sections of the table that have data.  There are really 2 scenarios:
1. show ONLY history sections (!concept.active&& concept.synonymsCt==0)
2. show all details sections (concept.synonymsCt>0)

Basically if there are any synonyms we should show all sections.  ONLY inactive UMLS CUIs will have no synonyms.  Inactive NCIt things should still display all sections.

**Comment by twkatadin** [comment]
Fixed inactive concepts to show all sections if synonyms are present

**Review by bcarlsenca — APPROVED** [review]
Thanks, mergin

**Pull request merged**
