### PR TITLE
[RDFBROWSER-312] License decline/escape fix

### PR DESCRIPTION
**Pull request by gaaliciA1990**
Implemented the changes requested in [RDFBROWSER-312](https://tracker.nci.nih.gov/browse/RDFBROWSER-312). 

1. When the user selects a terminology from the drop down on the welcome page that has a license requirement, the pop up now has a decline button. If the use clicks decline, the page will redirect to the main /welcome page and reload the original state. Additionally, if the user escapes out of the license, the same behavior is implemented.
2. When the user uses the multsearch feature from the dropdown and selects a terminology with a license requirement on the form, the checkbox is checked and the license window pops up to show the same accept and decline buttons. If the user selects decline, the terminology is unchecked. If the user escapes from the popup window, the terminology is also unchecked

Other updates were made in this update: 
- Changed all `==` to `===`. When we are doing comparisons, we don't want a loose equality, which will conduct a type coercion, allowing a `number = 1` to be a true comparison to `string = '1'`. The triple equals is a strict equality comparison, so the afore mentioned example will correctly return false.
- Changes all `!=` to `!==`. This is for the same reasons mentioned above, we want strict equality comparisons. 
- Changes all `var` to `let`/`const` depending on whether the variable is reassigned. Given all of the instances of `var` were locally scoped, not globally, we want to control how they are carried throughout the code, so using `let`/`const` gives us more control of their usage and restricts them to the class/methods/loops they are declared in. 
- Additional code clean up was performed in various locations as well.

Tag was created from this branch and deployed on Dev environment. I have confirmed the functionality is working as expected. Please review the changes as well.

### CODE REVIEW

**Review by bcarlsenca — COMMENTED** [review]
Make sure to thest the "All But NCIM" and "Select All" features - something is getting errored out and taking over the page (test in separate incognito window so you can kill it easily)

**Review by peter-va — COMMENTED** [review]
All looks good to me. I'll test on dev after the changes Brian mentioned.

**Comment by gaaliciA1990** [comment]
New bug found with Subsets link returning a `JSON.parse: unexpected character at line 1 column 1 of the JSON data` error. Moving to draft until all issues are fixed

**Review by peter-va — APPROVED** [review]
Can't get on the VPN to properly test it at the moment, looks good otherwise

**Pull request merged**
