### PR TITLE
Rdfbrowser131

### PR DESCRIPTION
**Pull request by peter-va**
fixes issues with https://tracker.nci.nih.gov/browse/RDFBROWSER-131

### CODE REVIEW

**Comment by peter-va** [comment]
also solves https://tracker.nci.nih.gov/browse/RDFBROWSER-132

**Review by bcarlsenca — COMMENTED** [review]
Peter, from the file diff it looks like you added the new paragraph but didn't remove the prior one (e.g. like it would show up twice).

**Comment by peter-va** [comment]
> Peter, from the file diff it looks like you added the new paragraph but didn't remove the prior one (e.g. like it would show up twice).

fixed with latest commits

**Review by bcarlsenca — APPROVED** [review]
OK, looks good

**Pull request merged**
