### PR TITLE
Rdfbrowser 212, 213, 214, 215

### PR DESCRIPTION
**Pull request by peter-va**
212: https://tracker.nci.nih.gov/browse/RDFBROWSER-212 - MedDRA display - picklist to choose terminology
213: https://tracker.nci.nih.gov/browse/RDFBROWSER-213 - MedDRA display - concept details
214: https://tracker.nci.nih.gov/browse/RDFBROWSER-214 - MedDRA display - header items
215: https://tracker.nci.nih.gov/browse/RDFBROWSER-215 - Link to ClinVar Variation ID

215 can't be tested yet, 212/214 are tested and working, 213 is partially tested and waiting on reindexing to complete properly before full testing.

### CODE REVIEW

**Comment by peter-va** [comment]
confirmed 213 is working fine, still can't test 215 until clin vars appear in the data

**Review by bcarlsenca — COMMENTED** [review]
feedback on mdr:

1. The "source" select list shouldn't be visible on search page if it's not "ncit" or "nicm"

2. The "source" select list at the top of the "concept details" and "hierarchy details" pages should not be visible
   if its not "ncit" or "ncim"

3. The "hierarhcy" button on the browser should show for "mdr", but should go to /hierarchy/mdr/10005329
  - note: both ncit and mdr have specific codes that clicking "hierarchy" goes to (the first root code when roots
    are listed alphabetically).  Ideally the solution here is to avoid hardcoding the actual value and instead
    make a call to /concept/{terminology}/roots, then sort the results alphabetically by name and then choose the first code and use that.

4. In "Documentation->TermTypes" the "note on special rules" should only show up if it is "ncit".

**Comment by peter-va** [comment]
All feedback has been implemented

**Comment by peter-va** [comment]
I implemented all of the given feedback

**Review by bcarlsenca — COMMENTED** [review]
OK, the "hierarchy" view still has the source selection at the top, e.g. http://localhost:4200/hierarchy/mdr/10009727.

One other small thing. If you're in "ncit" or "ncim" mode and you choose some source filters - then you switch the termnology.  those source filters remain . So you can wind up with a "MedDRA" setting where there's a leftover source filter.  I'ts easy to get rid of, but when we change terminologies, we should effectively reset all of the search parameters, including the source list.

**Comment by peter-va** [comment]
changes made

**Pull request merged**
